### ISSUE TITLE
Cannot build with latest compiler

### ISSUE THREAD

**Issue by riley-martin** [rust-fractal/rust-fractal-gui#2]
I cannot build `rust-fractal-gui` with the latest nightly rustc. It gives an error saying that the macro `llvm_asm!` could not be found while building crate `parking_lot`. Apparently this macro has been removed since rustc version `nightly-2022-01-17`. The version of `parking_lot` in `Cargo.toml` is `0.11.1`, but there has since been a new minor release (`0.12`) which uses the new `asm!` macro.  
Is there a good reason not to upgrade the dependency, or is there a specific date for the nightly rustc I should be using or something like that?

**Comment by jackyarndley** [comment]
Hi, thanks for the report. There is no reason to not upgrade the dependency.

I'm currently working on a new version using a different GUI framework (egui) where these issues have been fixed, and I am using the latest version there without issue.
